version 1.3

diff --git a/subto b/subto
--- a/subto
+++ b/subto
@@ -1,11 +1,13 @@
 #!/bin/bash
-# Written by Nikhilesh Gupta, December 2023 [ Last Updated At : June 2024 ]
+# Written by Nikhilesh Gupta, December 2023 [ Last Updated At : August 2024 ]
 
 # Define color codes
 RED='\033[0;31m'
-YELLOW='\033[1;33m'
+YELLOWB='\033[1;33m'
+YELLOW='\033[0;33m'
 BLUE='\033[0;34m'
 GREEN='\033[0;32m'
+GREENB='\033[1;32m'
 CYAN='\033[0;36m'
 MAGENTA='\033[0;35m'
 NC='\033[0m' # No Color
@@ -13,91 +15,173 @@ NC='\033[0m' # No Color
 
 # Function contains HELP information related to the script
 help_and_syntax_section() {
-        printf "${YELLOW}[+]Syntax for tool SUBTO{Subdomain-TakeOver}:${NC}\n";
+        printf "${YELLOWB}[+]Syntax for tool SUBTO{Subdomain-TakeOver}:${NC}\n";
+        printf "   -> ${CYAN}subto -d <subdomain> ${NC}\n"; 
         printf "   -> ${CYAN}subto -f <file.txt>${NC}\n";
-        printf "   -> ${CYAN}subto -d <domain.com>${NC}\n";
-        printf "${YELLOW}[#]Description:${NC} ${BLUE}The tool will check if the provided subdomains are vulnerable to Subdomain TakeOver attack${NC}\n";
-	printf "${YELLOW}[#]Note:${NC} ${BLUE}The file should have the list of subdomains{sub.example.com} seperated with next line${NC}\n";
+        printf "${CYAN}   Optional Flags:${NC}\n"
+        printf "     ${GREEN}-s${NC} # To only fetch data which have cloud CNAME records ${MAGENTA}[Only works with '-f' flag]${NC}\n"
+        printf "${YELLOWB}[#]Description:${NC} ${BLUE}The tool will check if the provided subdomains are vulnerable to Subdomain TakeOver attack${NC}\n";
+        printf "${YELLOWB}[#]Note:${NC} ${BLUE}The file should have the list of subdomains{sub.example.com} seperated with next line${NC}\n";
 
         exit 0;
 }
 
-# HELP | Checks if the Input is NULL
-if [[ $1 = '-h' ]] || [[ -z $1 ]]
-then
-        help_and_syntax_section
-fi;
+# Funtion to check Subdomain Takeover for a list of domains!!
+subdomain_takeover_check_for_list_of_subdomains() {
+        allDomains=$(tr '\n' ', ' < "$file");
+        allDomains=${allDomains%,}
 
-#Code for the list of domains!!
-if [ $1 = '-f' ]
-then
-        if [ ! -f $2 ]
-        then
-                echo "[!]File doesn't exists. Please check the path again"
-
-                exit 20;
-        fi;
-        allDomains=`cat $2`;
-
-        echo "[+]Input file - $2";
+        echo "[+]Input file - $file";
         echo "[+]Target Details - $allDomains";
         date;
+        echo "";
 
-        for subdomain in `cat $2`; do
-                cname=$(dig CNAME $subdomain | grep CNAME | grep -e azure -e aws);
+        for sub_domain in `cat $file`; do
+                cname=$(dig CNAME $sub_domain | grep CNAME | grep -e azure -e aws);
                 if [[ ! -z $cname ]]
                 then
                         record=$(echo $cname | awk '{ print $NF }');
                         #echo $record;
-                        status=$(dig CNAME $record | grep status: | cut -d "," -f2);
+                        status=$(dig $record | grep status: | cut -d "," -f2 | tr -d '[[:blank:]]');
                         #echo $status;
-                        if [[ $status = "status: NXDOMAIN" ]]
+                        if [[ "$status" == "status:NXDOMAIN" ]]
                         then
-                                echo "[+]Asset: $subdomain | CNAME $record |$status | Possible Subdomain Takeover";
+                                # echo "[+]Asset: $sub_domain | CNAME $record |$status | Possible Subdomain Takeover";
+                                printf "${GREENB}[+]Asset: $sub_domain | CNAME $record | $status | Possible Subdomain Takeover${NC}\n";
                         else
-                                echo "[-]Asset: $subdomain | CNAME $record |$status | Takeover (might) Not Possible";
+                                # echo "[!]Asset: $sub_domain | CNAME $record |$status | Takeover (might) Not Possible";
+                                printf "${YELLOW}[!]Asset: $sub_domain | CNAME $record | $status | Takeover (might) Not Possible${NC}\n";
                         fi;
                 else
-                        echo "[!]CNAME doesn't exists for $2";
+                        if [ "$silent_data_switch" != "true" ]; then
+                                printf "${RED}[-]CNAME doesn't exists for $sub_domain${NC}\n"
+                        fi;
         fi;
         done;
+}
 
-#Code for a single domain!!
-elif [ $1 = '-d' ]
-then
-        if [ -z $2 ]
-        then
-                echo "[!]No Domain was entered!!! Please use '-h' for help"
-                exit 20;
-        fi;
 
-        echo "[+]Target Domain - $2";
+# Funtion to check Subdomain Takeover for a single domain!!
+subdomain_takeover_check_for_subdomain() {
+        echo "[+]Target Domain - $subdomain";
         date;
+        echo "";
 
-        #progress=1;
-        cname=$(dig CNAME $2 | grep CNAME | grep -e azure -e aws);
+        cname=$(dig CNAME $subdomain | grep CNAME | grep -e azure -e aws);
         if [[ ! -z $cname ]]
         then
                 record=$(echo $cname | awk '{ print $NF }');
                 #echo $record;
-                status=$(dig CNAME $record | grep status: | cut -d "," -f2);
-                #echo $status;
-                if [[ $status = "status: NXDOMAIN" ]]
+                status=$(dig $record | grep status: | cut -d "," -f2 | tr -d '[[:blank:]]');
+                echo $status;
+                if [[ "$status" == "status:NXDOMAIN" ]]
                 then
-                        echo "[+]Asset: $2 | CNAME $record |$status | Possible Subdomain Takeover";
+                        # echo "[+]Asset: $subdomain | CNAME $record | $status | Possible Subdomain Takeover";
+                        printf "${GREENB}[+]Asset: $subdomain | CNAME $record | $status | Possible Subdomain Takeover${NC}\n";
                 else
-                        echo "[-]Asset: $2 | CNAME $record |$status | Takeover (might) Not Possible";
+                        # echo "[-]Asset: $subdomain | CNAME $record |$status | Takeover (might) Not Possible";
+                        printf "${YELLOW}[!]Asset: $subdomain | CNAME $record | $status | Takeover (might) Not Possible${NC}\n";
                 fi;
         else
-                echo "[!]CNAME doesn't exists for $2";
+                printf "${RED}[-]CNAME doesn't exists for $subdomain${NC}\n"
         fi;
+}
 
-        #       echo -en "[<=>]Progress : $((11*$progress))%";
-        #       progress=$progress+1;
+check_for_mandatory_flag() {
+	if ! $is_mandatory_flag_set; then
+		printf "${RED}[-]Error: Mandatory flag is not provided, please refer to examples provided in help section${NC}\n\n"
+
+		exit 1;
+
+	fi;
+}
+
+multiple_mandatory_flag_error() {
+        printf "${RED}[-]Error: Multiple flags provided, please refer to examples provided in help section${NC}\n\n"
+
+        exit 1
+}
 
 
-#Checks if the inputed value is incorrect!!
+# Assigning variables for user input
+subdomain="" # takes a single subdomain
+file="" # takes file which contains the data
+is_mandatory_flag_set=false # to check if the mandatory flag is provided by the user or not (expect '-s', using atleast any other flag is mandatory)
+silent_data_switch=false # a switch to specify if the end-user only wants the most relevant information and avoid unrequired data
+flag="" # takes the mandatory flag specified by the end-user
+
+# Checking if no command-line arguments is provided
+if [[ -z $1 ]]; then
+    cli_arg=false
 else
-        printf "${RED}[-]Error: Invalid syntax used for the tool, kindly refer to the help section below${NC}\n\n";
+    cli_arg=true
+fi
+
+if $cli_arg
+then
+    # To check if -h flag is provided
+    if [[ $1 = '-h' ]]
+    then
         help_and_syntax_section
+    else
+        # Looping through the command-line arguments to parse flags and their values
+        while [[ $# -gt 0 ]]; do
+            case $1 in
+                -f)
+                    shift
+                    if [[ -z "$1" ]]; then
+                        printf "${RED}[-]Error: Flag provided but not defined: -f${NC}\n\n"
+                    else
+                        if $is_mandatory_flag_set
+                        then
+                                multiple_mandatory_flag_error
+                        fi
+                        file=$1
+                        is_mandatory_flag_set=true
+                        flag="f"
+                    fi
+                    ;;
+                -d)
+                    shift
+                    if [[ -z "$1" ]]; then
+                        printf "${RED}[-]Error: Flag provided but not defined: -d${NC}\n\n"
+                    else
+                        if $is_mandatory_flag_set
+                        then
+                                multiple_mandatory_flag_error
+                        fi
+                        subdomain=$1
+                        is_mandatory_flag_set=true
+                        flag="d"
+                    fi
+                    ;;
+                -s)
+                    silent_data_switch=true
+                    ;;
+                *)
+                    if [[ ! "$1" == *"-"* ]]; then
+			    printf "${RED}[-]Error: No flag is provided, please refer to examples provided in help section${NC}\n\n";
+
+			    exit 1;
+		    fi;
+
+                    printf "${RED}[-]Error: Unknown flag or incorrect way to use the flag: $1${NC}\n\n"
+		    exit 1;
+                    ;;
+            esac
+            shift
+        done
+
+        check_for_mandatory_flag
+
+        # Calling the function corresponding to the queried flag
+        if [[ $flag = "f" ]]; then
+                subdomain_takeover_check_for_list_of_subdomains
+        elif [[ $flag = "d" ]]; then
+                subdomain_takeover_check_for_subdomain
+        fi
+    fi;
+else
+    # If no argument is provided
+    help_and_syntax_section
 fi;
